stages:
  embed-training-data:
    matrix:
      embedding_type: [ prott5, esm2 ]
      dataset: ${datasets.train}
    cmd: >-
      python -m vespag embed
      data/train/${item.dataset}/sequences.fasta
      data/train/${item.dataset}/${item.embedding_type}_embeddings.h5
      -c data/huggingface_cache/${item.embedding_type}
      -e ${item.embedding_type}
    deps:
      - vespag/data/embeddings.py
      - vespag/__main__.py
      - data/test/${item.dataset}/sequences.fasta
    outs:
      - data/train/${item.dataset}/${item.embedding_type}_embeddings.h5

  embed-test-data:
    matrix:
      embedding_type: [ prott5, esm2 ]
      dataset: ${datasets.test}
    cmd: >-
      python -m vespag embed
      data/test/${item.dataset}/sequences.fasta
      data/test/${item.dataset}/${item.embedding_type}_embeddings.h5
      -c data/huggingface_cache/${item.embedding_type}
      -e ${item.embedding_type}
    deps:
      - vespag/data/embeddings.py
      - vespag/__main__.py
      - data/test/${item.dataset}/sequences.fasta
    outs:
      - data/test/${item.dataset}/${item.embedding_type}_embeddings.h5

  preprocess-gemme-annotations:
    foreach: ${datasets.train}
    do:
      cmd: python -m vespag.data.gemme load ${item.gemme.raw} ${item.gemme.processed}

  train:
    matrix:
      model: ${models}
      embedding_type: [ prott5, esm2 ]
      dataset: ${datasets.train}
    cmd: >-
      python -m vespag train
      --model ${item.model}
      --dataset ${item.dataset}
      -o ./checkpoints/${item.dataset}/${item.embedding_type}/${item.model}/naive_sampling/
      -e ${item.embedding_type}
      --wandb ${wandb.username} ${wandb.project}
      --full-train-loss
      --sampling-strategy ${training.single_taxon.sampling_strategy}
    deps:
      - vespag/training/train.py
      - vespag/training/dataset.py
      - vespag/training/trainer.py
      - vespag/models
      - data/train/${item.dataset}/gemme_predictions.h5
    params:
      - datasets
      - random
      - training
      - models
    outs:
      - checkpoints/${item.dataset}/${item.embedding_type}/${item.model}/naive_sampling/
