name: Run tests and quality checks

on: [push, pull_request]

jobs:
  tests:
    name: 3.10 / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install package
        run: uv pip install .

      - name: Install dev dependencies
        run: uv pip install -r pyproject.toml --extra dev

      - name: Run nox sessions
        run: uv run nox
